### ISSUE TITLE
Add artist page feature

### ISSUE THREAD

**Issue by mimi89999** [EragonJ/Kaku#171]
Like in Atraci:
https://www.youtube.com/watch?v=vtT0rrDl4hg

**Comment by EragonJ** [comment]
This is a huge work because there is no such backend for us to support this. In order to make this happen, we need a team of editors and build databases for different singers with right album info with right track info.

To be short, this is not a easy work, even for iTunes, they must have a whole team and bunch of data to make this happen. No matter how, mark a feature label for this issue at the moment.

**Comment by EragonJ** [comment]
Close this feature because it's hard to implement this and it's an old issue.
