### ISSUE TITLE
"Unknown Artist" under some tracks

### ISSUE THREAD

**Issue by mimi89999** [EragonJ/Kaku#172]

**Comment by Draxler** [comment]
"Unknown Artist" can be seen on a lot of videos. Usualy only ''official'' videos have proper markingins, which means Title and Artis are showen corectly by seperation, each in own row, (Tilte in own row and Artist in own row).
"Unknown Artist" have another issue becaue now every ''Unknown Aritist'' video (which means a lot of videos) shows Title and Artist together in first row of the video, so user can see only artis name but not the title of the video (track). Which means if user search for some artist and get results back user couldn't see which track of this artis is the track he/she want to listen first, because user couldn't see the title because it's hiden.. Maybe if this issue could be solved by ''moving or running'' title. Which means when user hover over video title, title it self start movig from left to the right, from the beging to the end of the title, so user could see the whole video title.

![not234](https://cloud.githubusercontent.com/assets/7681671/8596866/234e5868-2652-11e5-9d4c-9a4c21c1bc90.PNG)

Not one video here have been proper marked (and there is much more such marked videos then proper ones). All of them have ''Unknown Artis'' which couse you couldn't see the title of the song of certain artis becuase all you see is the artist name.

**Comment by EragonJ** [comment]
Because from the API, we can't get any information like that. What we get is who (user) uploaded the track but normally this is not what we want. In this way, the default wording - `unknown artist` is shown. In order to fix this, need a powerful search engine or something that can help us match out the right information. 

Or ! We have to implement a feedback system and let users help us provide this info, with this data, we can implement our own mapping to make them look nice.

While for the problem you mentioned that you can't see the whole title at the first glimpse, I did add a `title` attribute on the tag and when you move your mouse on it and wait for about 1 sec, the whole title will show up, please give it a try.

**Comment by mimi89999** [comment]
![capture du 2015-07-10 11 38 48](https://cloud.githubusercontent.com/assets/8530546/8615073/43272d4e-26f8-11e5-8a27-6865d7fc6b96.png)

**Comment by Draxler** [comment]
@EragonJ 

I can see on @mimi89999 screenshot that it looks realy good. 
Me personal have to wait for your next update to see this work for my self on my KaKu app :smile:  . Until then i'm satisfied with the solution i see in this screenshot.

**Comment by mimi89999** [comment]
@Draxler What platform are you using (Operating System)?

**Comment by Draxler** [comment]
@mimi89999 
I'm using Win7/64 OS (sorry, didn't see question before today).

Kaku latest 1.0.0 verson still have this issue. (i don't know if you guys worked on it for V1.0.0 relese, so i reported just in case.  (No pressure or anything like that) .

**Comment by EragonJ** [comment]
Use uploader's name as artist for now because we don't have a right way to really know which song maps to which singer especially we do support different searchers.
