### ISSUE TITLE
Download only sound

### ISSUE THREAD

**Issue by uirsevla** [EragonJ/Kaku#235]
When we try to download a music from Kaku it downloads the Video.

Take for example the music Blank Space from Taylor Swift.
* Download from Kaku -> http://prntscr.com/803124
* Download as mp3 from (http://www.youtube-mp3.org/) -> http://prntscr.com/8032nr
That's almost 10x the bandwidth/hard drive space consumed and probably most users only want the music not the video.

My idea is that we could split the download option into:
1. Download music*
2. Download video.

*For what i've seen Youtube API doesn't allow us to only download the music, so we would need to download the video and then take only the music and delete the said video using a 3rd party converter or make one.

**Comment by EragonJ** [comment]
Kaku is built based on `youtube-dl`, so should check useful options from https://github.com/rg3/youtube-dl/blob/master/README.md#format-selection

**Comment by EragonJ** [comment]
@uirsevla is working on this bug, so marked as `in progress`

**Comment by Draxler** [comment]
There is no issue with Download function (just tested / Win OS). Kaku download Video with AUDIO.  
This is what it sopose to do imo, or am i missing something here?

**Comment by EragonJ** [comment]
This is just an option for users to choose which format they want. dup with https://github.com/EragonJ/Kaku/issues/189

**Comment by Draxler** [comment]
@EragonJ 
Ok. Thanks for explaination.

**Comment by EragonJ** [comment]
@uirsevla Here comes some tips about how to implement this feature : 

1. You need to add a select/option in settings page to let users choose what format they want (Please check https://github.com/rg3/youtube-dl#format-selection)
2. When users choose needed format (good quality video / bad quality video / good quality audio ... ), you need to keep these references and pass that to TrackInfoFetcher.js.
3. If I am right, this is all you need to do because Kaku is modularized enough and technically, you don't need to worry about the others. They should work independently by themselves. 

And remember, make sure all searchers do work under these different formats. I think that's all ! Happy hacking !

**Comment by EragonJ** [comment]
I just helped to implement this feature, feel free to update based on it ! Thanks :+1:

**Comment by reddit-is-fun** [comment]
@EragonJ Can you confirm that Kaku only downloads the audio when streaming? I only want to save bandwidth, I have a low bandwidth cap.

**Comment by EragonJ** [comment]
@reddit-is-fun you can check the settings panel, it says `best audio & best video` there :) If you do change the pref, you would notice that only audio has been downloaded.

**Comment by reddit-is-fun** [comment]
@EragonJ I don't believe that's true. YouTube supports resolutions up to 8K and it would be insane to start streaming video at 7680 × 4320 resolution on a 720p monitor.
I have checked the settings, would like to know what "best" exactly means.

**Comment by EragonJ** [comment]
> Can you confirm that Kaku only downloads the audio when streaming?

If you use `best audio`, then only audio will be streamed in Kaku !

**Comment by EragonJ** [comment]
If I was wrong, can you provide some data or analytics results for that ? That would be helpful for me to dive into bug. thanks !
