### ISSUE TITLE
Add installer for all different platforms

### ISSUE THREAD

**Issue by EragonJ** [EragonJ/Kaku#311]
As title, especially for Windows user, we need to make an installer to let users easily install this application to their own storage easily.

https://github.com/maxogden/electron-packager/issues/33
https://github.com/loopline-systems/electron-builder
https://github.com/maxogden/electron-packager/issues/21

**Comment by HLFH** [comment]
@EragonJ 

Hi,

I guess it's related. When we launch the Kaku shortcut (with mouseover, I see the name "Electron") in the taskbar, another Kaku icon is launched ![kaku2](https://cloud.githubusercontent.com/assets/2359059/11476975/d2b81024-9785-11e5-8fe2-0fa8547249a6.PNG)

We don't have this duplicate issue with other apps.

**Comment by EragonJ** [comment]
What is kaku shortcut ?? I didn't get it because I am not windows user. Can you attach more screenshots about each step ? it would be helpful !

**Comment by HLFH** [comment]
I used to be a *threesome user* because I was using OS X - Windows - GNU/Linux. But yes, for specific reasons, Windows 10 is now my main OS.

![kaku1](https://cloud.githubusercontent.com/assets/2359059/11500518/fdf8d522-982d-11e5-875b-6f4da78340a5.PNG)
![kaku 2](https://cloud.githubusercontent.com/assets/2359059/11500584/541d4a28-982e-11e5-9920-d3b3768e02f0.PNG)
![kaku3](https://cloud.githubusercontent.com/assets/2359059/11500610/7995061a-982e-11e5-8e3d-58d9ce7d26da.PNG)
![kaku4](https://cloud.githubusercontent.com/assets/2359059/11500651/aae7fcf4-982e-11e5-8c21-edfea44dc759.PNG)
![kaku5](https://cloud.githubusercontent.com/assets/2359059/11500688/fd6a1cdc-982e-11e5-9664-ee752c32eec7.PNG)
![kaku6](https://cloud.githubusercontent.com/assets/2359059/11500718/3fca34cc-982f-11e5-9445-32303c8b3935.PNG)

**Comment by EragonJ** [comment]
oh i see thanks @HLFH ! this looks like Electron's bug ! I'll find sometime to write a patch for it and will ask you to verify the bug ! thanks !!

**Comment by EragonJ** [comment]
Not in a high priority now, so close first.
