### ISSUE TITLE
'npm install' fails with errors

### ISSUE THREAD

**Issue by mimi89999** [EragonJ/Kaku#338]

**Comment by mimi89999** [comment]
I'm using node v4.2.2.

**Comment by EragonJ** [comment]
You should attach any error log here to show us what you got what running `npm install`. And for node version, right now I am not planning to support 4+ version because there is no too much benefit for Kaku right now especially there are some 3rd party libraries may fail due to this.

So please use `nvm` and change your node version back to 0.10+ to build Kaku for the time being ! Thanks.
