### ISSUE TITLE
Search through ALL searchers

### ISSUE THREAD

**Issue by patrickbolle** [EragonJ/Kaku#391]
Hey, loving Kaku so far. Great job getting this up and running.

I'm hoping there could be an option for searching on all the different music platforms (youtube, soundcloud, vimeo), rather than just picking one at a time.

I'll be looking through the code to see if I can send in a PR with something hacked together.
Not sure if there will be conflicts with each of the "Searcher" elements though. We will seee!

Thanks

**Comment by EragonJ** [comment]
hi @patrickbolle, Hmm, this sounds interesting. 

If you read the source code, you'll notice that Searcher will try to retrieve each sub-searcher and use their own `search()` function to do the search. And because there is an select/option list for users to decide which searcher they gonna use, it would be a preference kept in LocalStorage and will be used next time when booting up.

The better solution here from my mind is that, you can try to make a new sub-searcher with the same API interface like the others. In its `search()` function, you'll iterate all sub-searchers' search() function and collect those data into one there. By doing so, you can also create a new preference called `All Searcher` or something in Settings page for users to use with.

Hope this information helps :) any patch is welcome !

**Comment by EragonJ** [comment]
I'll work on this one because I am working on refactoring seachers !
