### ISSUE TITLE
Feature request: Import/export to a standard format (human readable)

### ISSUE THREAD

**Issue by ebadi** [EragonJ/Kaku#462]
#### Feature request:
The current backup solution is not useful without an import backup feature. 
It would be nice to have an option to backup all playlists to a simple and stardard file format (.cvs, josn, xml) on exit and possible load them again from the same file on startup.

Sidenote: Plaintext files are easy to store in git and other version controlling systems and light to transfer between clients (e.g. home and work PC).

**Comment by EragonJ** [comment]
@ebadi I don't understand it, right now it's already in json format and export as .txt file. So basically it's already working as what you expected.

**Comment by ebadi** [comment]
- The .txt file is not importable to kaku. (also it does not support auto-export on exit /auto-import on start) 
 - I cannot find any json file containing the mentioned information in the application directory or ~/.config/kaku/ . If you show me such file, the previous feature(auto export/auto-import) is not needed.

**Comment by EragonJ** [comment]
@ebadi if you can't import from local, i remembered there is one bug talking about that and it got solved in next release (1.8.0). So this should be invalid soon. While for the auto-export / auto-import feature, this is not needed because all playlist will be kept in local database. So when Kaku got boot up, it will load the data from database.

for question two, you need to click [settings panel] > [backup to localhost] and there will be one dialog popping out and ask you where to keep the file.

**Comment by ebadi** [comment]
Maybe you are right, maybe I cannot use the feature because of the bug. I will wait for the next version :) 
Thanks

**Comment by EragonJ** [comment]
cool thanks @ebadi ! working on 1.8.0 now, will be released soon this week

**Comment by EragonJ** [comment]
let me close this issue first.
