### ISSUE TITLE
When do Kaku update with new words?

### ISSUE THREAD

**Issue by olgi3rd** [EragonJ/Kaku#464]
#### Others

Hello, I modified some Korean words on Transifex.

When it update?

**Comment by EragonJ** [comment]
@olgierd-on-fire working on 1.8.0, sorry for waiting so long but it takes time for me to make sure things are working fine :) will be released within these two weeks

**Comment by olgi3rd** [comment]
@EragonJ All right. It's a stupid question that how is difficult to learn node.js to create such your application? I know Java and some JavaScript.

**Comment by EragonJ** [comment]
@olgi3rd if you already know some parts of javascript, then things should be easy. For Kaku, TBH there is no much backend code (node.js), because almost everything you see is basic a live website which is wrapped inside electron.

So back to topic, if you do have some knowledge about javascript, basically you can make another Kaku-like application (website) from now on :)

**Comment by olgi3rd** [comment]
@EragonJ Thank you, I'm interested in Electron but it's difficult, yet. Someday, I hope to contribute code to Kaku.

**Comment by EragonJ** [comment]
@olgi3rd If you want to help, I think unit tests should be a good step to start your contribution because there is no risk to add them but they are also important to any project.
